### Análise de Dados de Vendas com Pandas

**Contexto**: Você é um analista de dados em uma loja online que vende produtos eletrônicos. Foi fornecido um conjunto de dados com informações sobre vendas. Seu objetivo é usar o Pandas para responder a perguntas específicas e obter insights.

**Dataset**: Crie um DataFrame com os seguintes dados (você pode copiar e colar no seu código):

```python
import pandas as pd

dados = {
    'Produto': ['Smartphone', 'Notebook', 'Tablet', 'Smartphone', 'Notebook', 'Tablet', 'Smartphone', 'Tablet'],
    'Categoria': ['Eletrônicos', 'Eletrônicos', 'Eletrônicos', 'Eletrônicos', 'Eletrônicos', 'Eletrônicos', 'Eletrônicos', 'Eletrônicos'],
    'Preço': [1200, 3500, 800, 1100, 4000, 850, 1300, 900],
    'Quantidade_Vendida': [10, 5, 8, 12, 3, 6, 15, 7],
    'Data_Venda': ['2023-10-01', '2023-10-01', '2023-10-02', '2023-10-02', '2023-10-03', '2023-10-03', '2023-10-04', '2023-10-04'],
    'Região': ['Sul', 'Norte', 'Sudeste', 'Sul', 'Nordeste', 'Sudeste', 'Norte', 'Sul']
}

df = pd.DataFrame(dados)
```

**Tarefas**:

1. **Exploração Inicial**:
   - Exiba as primeiras 5 linhas do DataFrame.
   - Verifique se há valores nulos no conjunto de dados.
   - Mostre os tipos de dados de cada coluna.

2. **Cálculos Básicos**:
   - Adicione uma nova coluna chamada `Receita` que calcula o valor total de cada venda (Preço * Quantidade_Vendida).
   - Calcule a receita total de todas as vendas.

3. **Análise por Agrupamento**:
   - Agrupe os dados por `Produto` e calcule a média de `Preço` e a soma de `Quantidade_Vendida` para cada produto.
   - Agrupe os dados por `Região` e calcule a receita total por região.

4. **Filtros**:
   - Filtre as vendas onde a `Quantidade_Vendida` é maior que 10.
   - Filtre as vendas realizadas na região `Sul` com preço superior a 1000.

5. **Extra (Desafio)**:
   - Converta a coluna `Data_Venda` para o formato datetime.
   - Crie uma nova coluna que indique o dia da semana de cada venda.
   - Identifique qual dia da semana teve a maior receita total.

**Dicas**:
- Use funções como `head()`, `isna()`, `info()` para a exploração inicial.
- Para cálculos, use operações vetoriais do Pandas (ex.: `df['nova_coluna'] = df['coluna1'] * df['coluna2']`).
- Para agrupamentos, use `groupby()` com funções como `mean()` e `sum()`.
- Para trabalhar com datas, use `pd.to_datetime()` e `.dt.day_name()`.

## 1. Imports e Configs

### 1.1 Imports

In [9]:
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# versões
print('=== VERSOES UTILIZADAS ===')
print(f'Python: {sys.version.split()[0]}')
print(f'Pandas: {pd.__version__}')
print(f'Numpy: {np.__version__}')
print(f'Seaborn: {sns.__version__}')

=== VERSOES UTILIZADAS ===
Python: 3.13.5
Pandas: 2.2.3
Numpy: 2.1.3
Seaborn: 0.13.2

### 1.2 Configs

In [6]:
# pandas
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 20)
pd.set_option('display.precision', 2)
pd.set_option('display.float_format', '{:.2f}'.format)

# seaborn
sns.set_theme(style="whitegrid", palette="pastel", font_scale=1.2)

## 2. Obtenção de dados

In [10]:
try:
    df = pd.DataFrame({
        'Produto': ['Smartphone', 'Notebook', 'Tablet', 'Smartphone', 'Notebook', 'Tablet', 'Smartphone', 'Tablet'],
        'Categoria': ['Eletrônicos', 'Eletrônicos', 'Eletrônicos', 'Eletrônicos', 'Eletrônicos', 'Eletrônicos', 'Eletrônicos', 'Eletrônicos'],
        'Preço': [1200, 3500, 800, 1100, 4000, 850, 1300, 900],
        'Quantidade_Vendida': [10, 5, 8, 12, 3, 6, 15, 7],
        'Data_Venda': ['2023-10-01', '2023-10-01', '2023-10-02', '2023-10-02', '2023-10-03', '2023-10-03', '2023-10-04', '2023-10-04'],
        'Região': ['Sul', 'Norte', 'Sudeste', 'Sul', 'Nordeste', 'Sudeste', 'Norte', 'Sul']
    })
    print("=== Dados Carregados ===")
except exception as e:
    print(f'Erro ao carregar dataframe:\n{e}')

=== Dados Carregados ===

## 3. Tarefas

### 3.1 Exploração Inicial
- Exiba as primeiras 5 linhas do DataFrame.
- Verifique se há valores nulos no conjunto de dados.
- Mostre os tipos de dados de cada coluna.

In [11]:
# primeiras 5 linhas
df.head()

      Produto    Categoria  Preço  Quantidade_Vendida  Data_Venda    Região
0  Smartphone  Eletrônicos   1200                  10  2023-10-01       Sul
1    Notebook  Eletrônicos   3500                   5  2023-10-01     Norte
2      Tablet  Eletrônicos    800                   8  2023-10-02   Sudeste
3  Smartphone  Eletrônicos   1100                  12  2023-10-02       Sul
4    Notebook  Eletrônicos   4000                   3  2023-10-03  Nordeste

In [12]:
# check nulls
df.isnull().any()

Produto               False
Categoria             False
Preço                 False
Quantidade_Vendida    False
Data_Venda            False
Região                False
dtype: bool

In [13]:
# data types
df.dtypes

Produto               object
Categoria             object
Preço                  int64
Quantidade_Vendida     int64
Data_Venda            object
Região                object
dtype: object

### 3.2 Cálculos Básicos
- Adicione uma nova coluna chamada Receita que calcula o valor total de cada venda (Preço * Quantidade_Vendida).
- Calcule a receita total de todas as vendas.

In [14]:
# add atributo receita
df['Receita'] = df['Preço']*df['Quantidade_Vendida']
df.head(3)

,Produto,Categoria,Preço,Quantidade_Vendida,Data_Venda,Região,Receita
0,Smartphone,Eletrônicos,1200,10,2023-10-01,Sul,12000
1,Notebook,Eletrônicos,3500,5,2023-10-01,Norte,17500
2,Tablet,Eletrônicos,800,8,2023-10-02,Sudeste,6400

In [19]:
# receita total
print(df.Receita.sum())

92000

### 3.3 Análise por Agrupamento
- Agrupe os dados por Produto e calcule a média de Preço e a soma de Quantidade_Vendida para cada produto.
- Agrupe os dados por Região e calcule a receita total por região.

In [22]:
# agrupados por produto com média de preço e soma da quantidade vendida
(
    df.groupby('Produto')
     .agg({'Preço':'mean', 'Quantidade_Vendida':'sum'})
     .rename(columns={'Preço': 'Preço_Médio', 'Quantidade_Vendida': 'Total_Vendido'})
)

            Preço_Médio  Total_Vendido
Produto
Notebook        3750.00              8
Smartphone      1200.00             37
Tablet           850.00             21

In [23]:
# agrupados por regiao com receita total
df.groupby('Região')['Receita'].sum()

Região
Nordeste    12000
Norte       37000
Sudeste     11500
Sul         31500
Name: Receita, dtype: int64

### 3.4 Filtros
- Filtre as vendas onde a Quantidade_Vendida é maior que 10.
- Filtre as vendas realizadas na região Sul com preço superior a 1000.

In [24]:
# vendas  = quantidade vendida > 10
df[df['Quantidade_Vendida']>10]

,Produto,Categoria,Preço,Quantidade_Vendida,Data_Venda,Região,Receita
3,Smartphone,Eletrônicos,1100,12,2023-10-02,Sul,13200
6,Smartphone,Eletrônicos,1300,15,2023-10-04,Norte,19500

In [34]:
# vendas regiao sul = preco > 1000
df[(df['Região']=='Sul') & (df['Preço']>1000)]
#df.query("Região == 'Sul' and Preço > 1000")

,Produto,Categoria,Preço,Quantidade_Vendida,Data_Venda,Região,Receita
0,Smartphone,Eletrônicos,1200,10,2023-10-01,Sul,12000
3,Smartphone,Eletrônicos,1100,12,2023-10-02,Sul,13200

### 3.5 Extra (Desafio)
- Converta a coluna Data_Venda para o formato datetime.
- Crie uma nova coluna que indique o dia da semana de cada venda.
- Identifique qual dia da semana teve a maior receita total.

In [36]:
# converter atributo para formato date
df['Data_Venda']=pd.to_datetime(df['Data_Venda'])
df.dtypes

Produto                       object
Categoria                     object
Preço                          int64
Quantidade_Vendida             int64
Data_Venda            datetime64[ns]
Região                        object
Receita                        int64
dtype: object

In [43]:
# atributo dia da semana
df['Dia_Semana'] = df['Data_Venda'].dt.day_name()
df.head()

,Produto,Categoria,Preço,Quantidade_Vendida,Data_Venda,Região,Receita,Dia_Semana
0,Smartphone,Eletrônicos,1200,10,2023-10-01,Sul,12000,Sunday
1,Notebook,Eletrônicos,3500,5,2023-10-01,Norte,17500,Sunday
2,Tablet,Eletrônicos,800,8,2023-10-02,Sudeste,6400,Monday
3,Smartphone,Eletrônicos,1100,12,2023-10-02,Sul,13200,Monday
4,Notebook,Eletrônicos,4000,3,2023-10-03,Nordeste,12000,Tuesday

In [45]:
# dia da semanha com maior receita
df.groupby('Dia_Semana')['Receita'].sum().idxmax()

'Sunday'